services:
  - type: web
    name: ppt-title-extractor
    env: python
    buildCommand: ./build.sh
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 